gitlab_athlone:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: '10.44.147.246'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://10.44.147.246'
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'